version: '3'

services:

  wallet-db:
    image: postgres
    container_name: wallet-db
    env_file:
      - ./config/db.env
    ports:
      - "8432:5432"

  wallet-cms:
    build: ./wallet-cms
    container_name: wallet-cms
    depends_on:
      - "wallet-db"
    env_file:
      - ./wallet-cms/.env
    ports:
      - "8000:8080"

  wallet-blockchain:
    build: ./wallet-blockchain
    container_name: wallet-blockchain
    depends_on:
      - "wallet-db"
      - "wallet-cms"
    env_file:
      - ./wallet-blockchain/.env
    ports:
      - "8001:8080"
