version: '3'

services:

  wallet-db:
    container_name: wallet-db
    image: postgres:15.2
    ports:
      - "8432:5432"
    env_file:
      - ./production.env

  wallet-server:
    container_name: wallet-server
    build: ./wallet-server
    depends_on:
      - "wallet-db"
    ports:
      - "8000:8000"
    env_file:
      - ./production.env
