version: '3'

services:

  wallet-db:
    image: postgres
    container_name: wallet-db
    ports:
     - "8432:5432"

  wallet-cms:
    build: ./wallet-cms
    container_name: wallet-cms
    depends_on:
     - "wallet-db"
    ports:
     - "8000:8080"
    env_file:
     - ./config/cms.env
